# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-04 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_item_presentacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='unit_price_base',
        ),
    ]
