# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-04 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_item_unit_price_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='codigo',
            field=models.CharField(default='FFFF', max_length=400, verbose_name='Código'),
            preserve_default=False,
        ),
    ]
