# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-05 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(blank=True, help_text='Ingrese la url actual del sitio sin el slash final', max_length=60, verbose_name='URL del sitio')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Para correos')),
                ('taxi', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Taxi por Envío')),
            ],
        ),
    ]
