# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-04 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='pedido',
        ),
        migrations.DeleteModel(
            name='PedidoItem',
        ),
    ]
