# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-04 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=180, verbose_name='slug')),
                ('position', models.SmallIntegerField(default=0, verbose_name='Posición')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre del Curso')),
                ('position', models.SmallIntegerField(default=0, verbose_name='Posición')),
                ('codigo', models.CharField(max_length=400, verbose_name='Código')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio Referencia')),
                ('img_curso', filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name='Imagen del Curso')),
                ('fk_categoria', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_cat', to='productos.Categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name_plural': 'Curso',
                'verbose_name': 'Curso',
            },
        ),
    ]
