# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-04 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='mostrar_home',
            field=models.BooleanField(default=False, verbose_name='¿Mostrar en el Home?'),
        ),
    ]
