# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-04 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_curso_mostrar_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='fk_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_cat', to='productos.Categoria', verbose_name='Categoria'),
        ),
    ]
