METHOD_STRIPE = 1
METHOD_PAYPAL = 2
METHOD_BANK_TRANSFER = 3
METHOD_CASH_PAYMENT_OXXO = 4
METHOD_CASH_PAYMENT_EFECTY = 5
METHOD_MANUAL_ORDER = 6
METHOD_PAYU = 7
METHOD_PAGO_EFECTIVO = 8
METHOD_PAGO_NONE = 9
METHOD_CULQI = 10

METHOD_CHOICES = (
    (METHOD_STRIPE, 'Stripe'),
    (METHOD_PAYPAL, 'Paypal'),
    (METHOD_BANK_TRANSFER, 'Bank Transfer'),
    (METHOD_CASH_PAYMENT_OXXO, 'Compropago'),
    (METHOD_CASH_PAYMENT_EFECTY, 'Epayco'),
    (METHOD_MANUAL_ORDER, 'Manual'),
    (METHOD_PAYU, 'PayU'),
    (METHOD_PAGO_EFECTIVO, 'Pago efectivo'),
    (METHOD_CULQI, 'Culqi'),
    (METHOD_PAGO_NONE, 'Sin metodo'),
)
